#!/usr/bin/env python3
"""One palette for every agent: Catppuccin Mocha plus the kitty accent.

    python3 palette.py            read the accent from kitty's accents/current.conf, rewrite the generated files
    python3 palette.py --check    say what would change, change nothing

Writes, next to this file:
  palette.json                 the colours, read by statusline.py on every render

`kitty-accent` calls this after every switch, so the statusline follows the accent picker.
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ACCENT_CONF = os.path.expanduser('~/.config/kitty/accents/current.conf')
MOCHA = {
    'rosewater': '#f5e0dc', 'flamingo': '#f2cdcd', 'pink': '#f5c2e7', 'mauve': '#cba6f7', 'red': '#f38ba8',
    'maroon': '#eba0ac', 'peach': '#fab387', 'yellow': '#f9e2af', 'green': '#a6e3a1', 'teal': '#94e2d5',
    'sky': '#89dceb', 'sapphire': '#74c7ec', 'blue': '#89b4fa', 'lavender': '#b4befe', 'text': '#cdd6f4',
    'subtext1': '#bac2de', 'subtext0': '#a6adc8', 'overlay2': '#9399b2', 'overlay1': '#7f849c',
    'overlay0': '#6c7086', 'surface2': '#585b70', 'surface1': '#45475a', 'surface0': '#313244',
    'base': '#1e1e2e', 'mantle': '#181825', 'crust': '#11111b',
}


def read_accent():
    """(name, hex) of the persisted kitty accent; mauve when kitty has none."""
    try:
        text = open(ACCENT_CONF).read()
    except OSError:
        return 'mauve', MOCHA['mauve']
    name = re.match(r'#\s*([a-z]+)\b', text)
    colour = re.search(r'^cursor\s+(#[0-9a-fA-F]{6})', text, re.M)
    hexv = colour.group(1).lower() if colour else MOCHA['mauve']
    return (name.group(1) if name else 'custom'), hexv


def palette():
    name, accent = read_accent()
    return {
        '_comment': 'Generated by palette.py from Catppuccin Mocha + the kitty accent. Do not edit; run kitty-accent.',
        'accent_name': name,
        'colors': dict(MOCHA, accent=accent),
        # What each statusline element is drawn in, so every agent means the same thing by a colour.
        'roles': {'badge_bg': 'accent', 'badge_fg': 'crust', 'model': 'accent', 'effort': 'peach', 'dir': 'sky',
                  'branch': 'green', 'dirty': 'yellow', 'clean': 'green', 'ok': 'green', 'warn': 'yellow',
                  'bad': 'red', 'cost': 'peach', 'claims': 'teal', 'memory': 'lavender', 'sep': 'surface2',
                  'dim': 'overlay1'},
        'accounts': {'main': 'blue', 'cx': 'peach', 'cm': 'green', 'codex': 'teal', 'opencode': 'accent',
                     'dsh': 'sapphire', 'kimi': 'maroon', 'grok': 'rosewater'},
    }


def write(path, obj, check):
    text = json.dumps(obj, indent=2) + '\n'
    try:
        same = open(path).read() == text
    except OSError:
        same = False
    if same:
        return False
    print(('would write ' if check else 'wrote ') + path)
    if not check:
        tmp = path + '.tmp'
        with open(tmp, 'w') as f:
            f.write(text)
        os.replace(tmp, path)
    return True


def main():
    check = '--check' in sys.argv[1:]
    p = palette()
    changed = write(os.path.join(HERE, 'palette.json'), p, check)
    if not changed:
        print(f'palette up to date (accent {p["accent_name"]} {p["colors"]["accent"]})')
    return 0


if __name__ == '__main__':
    sys.exit(main())
